### PR TITLE
Mark simple marcos as const instead of static

### PR DESCRIPTION
**Pull request by qmfrederik**
A lot of the FFmpeg macros are really simple declarations such as `AV_BUFFER_FLAG_READONLY = 1 << 0`.

This PR changes the generator so that it recognizes constant expressions which are integer constants, or a bitwise operator on two integer constants and generates them as `const` instead of `static`.

I noticed this when I wanted to define an `enum` based on some of the macros (codec capabilities in my case), but values need to be constant before being able to use them in an enum.

### CODE REVIEW

**Comment by qmfrederik** [comment]
I split the PR in three commits; hoping it makes it easier to review the changes.

**Comment by Ruslan-B** [comment]
Hi @qmfrederik , I would wait with this pull request as I'm addressing this issue now https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/63 . To address the issue I need more sophisticated macro parser which I'm building right now https://github.com/rational-core/ClangMacroParser.
I think I should be able to finish it during weekend.
Then I have plane to precompute all macroses as constants while keeping original body in xml doc.

**Comment by qmfrederik** [comment]
Sure, good luck!

**Comment by Ruslan-B** [comment]
I'm closing this request as if you would like to see const generated you need to change only one word in the writer, all of them can be considered as simple.

**Pull request closed without merging**
